# Generated by Django 3.1.7 on 2023-05-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('action', models.CharField(choices=[('opened', 'Open'), ('closed', 'Closed'), ('reopened', 'Reopened')], max_length=10)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Close')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('merge_commit_sha', models.CharField(max_length=40, null=True)),
                ('user', models.CharField(max_length=100)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='pull_request_screenshots/')),
            ],
            options={
                'db_table': 'pull_requests',
            },
        ),
    ]
