# Generated by Django 3.1.7 on 2023-05-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
