# Generated by Django 3.1.7 on 2023-05-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230519_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='screenshot',
            field=models.URLField(null=True),
        ),
    ]
