# Generated by Django 3.1.7 on 2023-05-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230520_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='screenshot',
            field=models.ImageField(upload_to='screenshots/'),
        ),
    ]
